apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  #Base64 String: postgres = cG9zdGdyZXM=
  #Base64 String: mysecretpassword = bXlzZWNyZXRwYXNzd29yZCA==
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: bXlzZWNyZXRwYXNzd29yZA==